controllers/AutoController.php
<?php

namespace app\controllers;


use app\models\Car;
use app\models\CarModel;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class AutoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'models' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [

        ]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $model = new Car();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('/profile/view');
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findUserModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('/profile/view');
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findUserModel($id);
        $model->status = Car::STATUS_DELETED;
        $model->save();

        return $this->redirect('/profile/view');
    }

    public function actionModels()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $id = Yii::$app->request->post('id');
        if (!$id) {
            return [];
        }

        return CarModel::find()->select(['id', 'name'])->where(['mark_id' => $id])->orderBy(['name' => SORT_ASC])->asArray()->all();
    }

    /**
     * @param $id
     * @return Car
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        $model = Car::find()->with(['user'])->where(['id' => $id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }

    /**
     * @param $id
     * @return Car
     * @throws NotFoundHttpException
     */
    protected function findUserModel($id)
    {
        $model = Car::find()->where(['id' => $id, 'user_id' => Yii::$app->user->id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\services\UserService;
use app\models\ContactForm;
use app\models\GeoTown;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\RestorePasswordForm;
use app\models\SearchForm;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\Response;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                    'town' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchForm = new SearchForm();

        return $this->render('index', [
            'searchForm' => $searchForm,
        ]);
    }

    /**
     * @return array
     */
    public function actionTown()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return GeoTown::findByTerm(Yii::$app->request->post('query'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRestorePassword()
    {
        $model = new RestorePasswordForm();

        if ($model->load(Yii::$app->request->post()) && $model->resetPassword() && $model->sendLetter()) {
            return $this->render('restore-letter-sent');
        }

        return $this->render('restore-password', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRegister()
    {
        $model = new RegistrationForm();

        if ($model->load(Yii::$app->request->post()) && $model->process()) {
            $user = $model->getUser();
            Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения регистрации');
            return $this->redirect(['/site/index']);
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $email
     * @param string $code
     * @return Response
     */
    public function actionConfirm($email, $code)
    {
        $user = User::findOne([
            'email' => $email,
            'confirm_code' => $code,
            'status' => User::STATUS_INACTIVE
        ]);

        if ($user === null) {
            Yii::$app->session->setFlash('error', 'Пользователь с такими данными не найден, либо не требует активации');
            return $this->redirect(['index']);
        }

        if (UserService::confirm($user)) {
            Yii::$app->session->setFlash('success', 'Ваш аккаунт активирован');
            Yii::$app->user->login($user);
            return $this->redirect(['/profile/view']);
        }

        Yii::$app->session->setFlash('error', 'Возникла непредвиденная ошибка. Обратитесь в службу поддержки');
        return $this->redirect(['index']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionCalculator()
    {
        return $this->render('calculator');
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionFeedback()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('feedback', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return string
     */
    public function actionSafety()
    {
        return $this->render('safety');
    }

    /**
     * @return string
     */
    public function actionRules()
    {
        return $this->render('rules');
    }

    /**
     * @return string
     */
    public function actionPartners()
    {
        return $this->render('partners');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */

/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);

/** @var \app\models\User $user */
$user = Yii::$app->user->identity;

$menuItems = [];
if (Yii::$app->user->isGuest) {
    $menuItems = [
        ['label' => 'Вход', 'url' => ['/site/login']],
        ['label' => 'Регистрация', 'url' => ['/site/register']],
    ];
} else {
    $menuItems = [
        [
            'label' => 'Профиль',
            'url' => ['/profile/view'],
        ],
        [
            'label' => 'Выход (' . $user->name . ')',
            'url' => '/site/logout/',
            'linkOptions' => ['data-method' => 'post']
        ],
    ];
}

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= $this->title ?></title>
    <?php $this->head() ?>
    <script src="https://vk.com/js/api/openapi.js?160" type="text/javascript"></script>

</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap container">
        <div class="container">
            <div class="jumbotron big-banner">
                <img src="/img/logo_bar.png" class="vert-margin40">
                <p class="lead home-title">Уже 58495 человек из России, Украины и Беларуси используют наш сайт чтобы экономить на
                    поездках на работу, учебу или путешествиях между городами </p>

            </div>
        </div>

    <div class="">
        <?php NavBar::begin([
            'brandLabel' => 'Попутчики.ру',
            'brandUrl' => Yii::$app->homeUrl,
            'options' => [
                'class' => 'navbar-default',
            ],
        ]); ?>
        <?php echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => \yii\helpers\ArrayHelper::merge([
                ['label' => 'Попутчики на автомобиле из города в город', 'url' => ['#']],
                ['label' => 'Попутчики отпуск заграницу', 'url' => ['#']],
                ['label' => 'Калькулятор расхода топлива', 'url' => ['/site/calculator']],
            ], $menuItems)
        ]); ?>
        <?php NavBar::end(); ?>
    </div>

    <div class="container">
        <!--<div class="header">
            <div class="row">
                <div class="col-md-3 col-sm-3">
                    <?= Html::a(Html::img('/img/logo_bar.png', ['alt' => 'Поехали вместе!']), '/'); ?>
                </div>
                <div class="col-md-6 col-sm-6 hidden-xs">
                    <div class="text" style="text-align: center;">Сервис поиска попутчиков</div>
                </div>
                <div class="col-md-3 col-sm-3">
                    <div class="text pull-right">
                        <?php if (Yii::$app->user->isGuest) { ?>
                            <?= Html::a('Вход', ['/site/login']); ?>
                            |
                            <?= Html::a('Регистрация', ['/site/register']); ?>
                        <?php } else { ?>
                            <?= Html::a(Html::encode($user->email), ['/profile/view']); ?>
                            |
                            <?= Html::a('Выход', ['/site/logout'], ['data-method' => 'post']); ?>
                        <?php } ?>
                    </div>
                </div>
            </div>
        </div>-->

        <?= Breadcrumbs::widget([
            'encodeLabels' => false,
            'homeLink' => [
                'label' => 'Попутчики',
                'url' => '/',
            ],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-2 col-sm-2">
                <h5>Администрация проекта</h5>
                info@povm.ru<br/>
                2012 ©
            </div>
            <div class="col-md-2 col-sm-2">
                <h5>Мы в соцсетях</h5>
            </div>
            <div class="col-md-2 col-sm-2">
                <h5>О сайте</h5>
                <ul>
                    <li><?= Html::a('Автопарк проекта', ['/auto/index']); ?></li>
                    <li><?= Html::a('Техника безопасности', ['/site/safety']); ?></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-2">
                <h5>Информация</h5>
                <ul>
                    <li><?= Html::a('Как это работает', ['/site/about']); ?></li>
                    <li><?= Html::a('Правила сервиса', ['/site/rules']); ?></li>
                    <li><?= Html::a('Обратная связь', ['/site/feedback']); ?></li>
                    <li><?= Html::a('Наши партнеры', ['/site/partners']); ?></li>
                </ul>
            </div>
            <div class="col-md-2 col-sm-2">
                <h5>География</h5>
                <?= \app\widgets\CountryWidget::widget(); ?>
            </div>
            <div class="col-md-2 col-sm-2">
                Счетчик
            </div>
        </div>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>