controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\services\UserService;
use app\models\ContactForm;
use app\models\GeoTown;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\RestorePasswordForm;
use app\models\SearchForm;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\Response;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                    'town' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchForm = new SearchForm();

        return $this->render('index', [
            'searchForm' => $searchForm,
        ]);
    }

    /**
     * @return array
     */
    public function actionTown()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return GeoTown::findByTerm(Yii::$app->request->post('query'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRestorePassword()
    {
        $model = new RestorePasswordForm();

        if ($model->load(Yii::$app->request->post()) && $model->resetPassword() && $model->sendLetter()) {
            return $this->render('restore-letter-sent');
        }

        return $this->render('restore-password', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRegister()
    {
        $model = new RegistrationForm();

        if ($model->load(Yii::$app->request->post()) && $model->process()) {
            $user = $model->getUser();
            Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения регистрации');
            return $this->redirect(['/site/index']);
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $email
     * @param string $code
     * @return Response
     */
    public function actionConfirm($email, $code)
    {
        $user = User::findOne([
            'email' => $email,
            'confirm_code' => $code,
            'status' => User::STATUS_INACTIVE
        ]);

        if ($user === null) {
            Yii::$app->session->setFlash('error', 'Пользователь с такими данными не найден, либо не требует активации');
            return $this->redirect(['index']);
        }

        if (UserService::confirm($user)) {
            Yii::$app->session->setFlash('success', 'Ваш аккаунт активирован');
            Yii::$app->user->login($user);
            return $this->redirect(['/profile/view']);
        }

        Yii::$app->session->setFlash('error', 'Возникла непредвиденная ошибка. Обратитесь в службу поддержки');
        return $this->redirect(['index']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionCalculator()
    {
        return $this->render('calculator');
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionFeedback()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('feedback', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return string
     */
    public function actionSafety()
    {
        return $this->render('safety');
    }

    /**
     * @return string
     */
    public function actionRules()
    {
        return $this->render('rules');
    }

    /**
     * @return string
     */
    public function actionPartners()
    {
        return $this->render('partners');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$title = 'О сайте';
$this->title = $title . ' - ' . Yii::$app->name;
$this->params['breadcrumbs'][] = $title;
?>
<div class="site-about">
    <h1>Поиск попутчиков &laquo;Поехали вместе&raquo;</h1>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <p>
                Этот сервис создан для тех людей, которые часто ездят из одного города в другой,
                как в роли пассажира на общественном транспорте, так и для водителей, которые передвигаются на личном авто.
                <br /><br />
                Последним этот сервис поможет сократить расходы на дорогу, взяв с собой попутчика, ведь разделив сумму на двоих
                (или троих), кошелек не так сильно страдает ;) Ну а пассажиром лучше ехать в комфортабельном автомобиле, чем в душном поезде
                или, того хуже, автобусе на узких сидениях и сами знаете с чем еще
            </p>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
    </div>
</div>

views/site/calculator.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */

$this->title = 'Калькулятор расхода топллива. Расход топлива на 100 км.';
$this->params['breadcrumbs'][] = $this->title;
?>
    <h1 class="vert-margin40">Калькулятор расхода топлива автомобилей</h1>
    <div class="row">
        <div class="col-sm-6">
            <h2 class="center-align vert-margin20">Калькулятор расхода топлива на расстояние</h2>
            <p class="center-align">Если вы планируете поездку и вам нужно расчитать объём и стоимость, необходимого
                топливана весь путь или его часть.</p>
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="distance" class="col-sm-6 control-label">Укажите расстояние</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('distance', 0, [
                                'id' => 'distance',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">км</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="consumption" class="col-sm-6 control-label">Средний расход топлива</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('consumption', 0, [
                                'id' => 'consumption',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">л / 100 км</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-6 control-label">Стоимость топлива за л.</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('price', 0, [
                                'id' => 'price',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">р/л</span>
                        </div>
                    </div>
                </div>

                <hr/>

                <div class="col-sm-12">
                    <div class="right-align">
                        <button type="button" class="btn btn-lg btn-default">Рассчитать расход</button>
                    </div>
                </div>
                <div class="col-sm-12">
                    <h4 class="vert-margin30">Результаты расчёта:</h4>
                </div>

                <div class="form-group">
                    <label for="total-fuel" class="col-sm-6 control-label">Итого расход топлива</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('total-fuel', 0, [
                                'id' => 'total-fuel',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">л / 500 км</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="total-price" class="col-sm-6 control-label">Итого стоимость</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('total-price', 0, [
                                'id' => 'total-price',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">руб</span>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-sm-6">
            <h2 class="center-align vert-margin20">Расход топлива на 100 км</h2>
            <p class="center-align">Если вам необходимо выяснить средний расход топлива вашего автомобиля, по факту
                совершения поездки</p>
            <form class="form-horizontal">
                <div class="form-group">
                    <label for="distance" class="col-sm-6 control-label">Пройденное расстояние</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('distance', 0, [
                                'id' => 'distance',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">км</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="total-fuel" class="col-sm-6 control-label">Израсходовано топлива</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('total-fuel', 0, [
                                'id' => 'total-fuel',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">л.</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-6 control-label">Стоимость топлива за л.</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('price', 0, [
                                'id' => 'price',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">р/л</span>
                        </div>
                    </div>
                </div>

                <hr/>
                <div class="col-sm-12">
                    <div class="right-align">
                        <button type="button" class="btn btn-lg btn-default">Рассчитать расход</button>
                    </div>
                </div>
                <div class="col-sm-12">
                    <h4 class="vert-margin30">Результаты расчёта:</h4>
                </div>
                <div class="form-group">
                    <label for="consumption" class="col-sm-6 control-label">Средний расход топлива</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('consumption', 0, [
                                'id' => 'consumption',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">л / 100 км</span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="total-price" class="col-sm-6 control-label">Средняя стоимость</label>
                    <div class="col-sm-6">
                        <div class="input-group">
                            <?= Html::textInput('total-price', 0, [
                                'id' => 'total-price',
                                'class' => 'form-control',
                            ]); ?>
                            <span class="input-group-addon">руб./ 1 км</span>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>

<?php $this->registerJs(
    <<<JS


JS
);

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/feedback.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$title = 'Обратная связь';
$this->title = $title . ' - ' . Yii::$app->name;
$this->params['breadcrumbs'][] = $title;
?>
<div class="site-contact">
    <h1><?= Html::encode($title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/index.php
<?php

use app\assets\Select2Asset;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $searchForm \app\models\SearchForm */

Select2Asset::register($this);

$this->title = 'Попутчики.РУ. Совместные поездки на машине';
?>

<div class="body-content">

    <div class="row">
        <div class="col-md-8 col-sm-8">
            <h1>Поиск попутчиков</h1>

            <div class="search-form">
                <?php $form = ActiveForm::begin([
                    'action' => ['/trip/search'],
                    'method' => 'get',
                    'options' => [
                        'id' => 'search-form',
                        'style' => 'margin:10px 0',
                    ],
                ]); ?>
                <?= Html::activeDropDownList($searchForm, 'from', [], [
                    'prompt' => 'Откуда едем',
                    'style' => 'width:25%height:34px;',
                    'class' => 'select-town',
                    'data-language' => 'ru',
                ]); ?>
                <?= Html::activeDropDownList($searchForm, 'to', [], [
                    'prompt' => 'Куда едем',
                    'style' => 'width:25%',
                    'class' => 'select-town',
                    'data-language' => 'ru',
                ]); ?>
                <?= Html::activeHiddenInput($searchForm, 'role'); ?>
                <?= Html::button('Найти пассажира', [
                    'class' => 'btn btn-default submit-search-form',
                    'data-role' => 1,
                ]); ?>
                <?= Html::button('Найти водителя', [
                    'class' => 'btn btn-default submit-search-form',
                    'data-role' => 2,
                ]); ?>
                <?php ActiveForm::end(); ?>
                <p><strong>Если вы не нашли нужную поездку</strong>, <?= Html::a('создайте свою', '#', [
                        'class' => 'create-link',
                    ]); ?>, и вас найдут ваши попутчики.</p>
            </div>

            <p>
                <?= \app\widgets\TripWidget::widget([
                    'title' => 'Ближайшие поездки',
                ]); ?>
            </p>

        </div>
        <div class="col-md-4 col-sm-4 hidden-xs">
            <?= Html::a('Найти попутчика', ['/trips/create/?step1/'], [
                'class' => 'btn btn-success btn-lg btn-block',
            ]); ?>
            <h2>Как найти попутчиков?</h2>
            <strong>Сделать это можно двумя способами:</strong> <br/><br/>
            <p><strong>Первый</strong> - воспользоваться формой поиска указав пункты отправления и прибытия,
                найти объявления о поиске попутчиков по вашему маршруту связаться с автором и договориться о месте
                встречи. Если вы не нашли нужную поездку, переходите ко второму способу.
                <br/> <br/>
                <strong>Второй</strong> - создать свое объявление о поиске попутчиков указав пункты "А" и "Б" с крайней
                датой отправления и ждать когда ваши попутчики свяжуться с вами.
            </p>
            <h3>Водителям</h3>
            <p>Указывайте количество свободного места в багажнике и количестве пассажиров которое вы берете, можно ли
                например взять с собой собаку будет ли для неё сбободное место и т.д. чем больше вы укажите дополнительной информации тем
                лучше. </p>
            <h3>Пассажирам</h3>
            <p>При создании поездки указывайте максимально полную информацию о количестве, характере и размере багажа,
                количестве человек и иную информацию, которая сможет водителю более подробно понять сможет ли он
                обеспечить вам конфортную поездку</p>
            <h3>Как поехать попутчиком на машине максимально безопасно?</h3>
            <p>Как выбрать попутчика чтобы доехать на машине "от" и "до"?</p>
            <p>Рассказываем:</p>
            <ol>
                <li>Выбирайте поездки с водителями аккаунты который заполнены максимально полно</li>
                <li>Смотрте историю поездок водителя</li>
                <li>Не ездите один, особенно если вы девушка</li>
                <li>Когда будете договариваться о месте встречи спросите сколько всего пасссажиров, чем больше людей тем безопаснее</li>
            </ol>
            <h2 class="vert-margin30">Поделиться с друзьями</h2>
            <script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
            <script src="//yastatic.net/share2/share.js"></script>
            <div class="ya-share2"
                 data-services="collections,vkontakte,facebook,odnoklassniki,twitter,lj,viber,whatsapp,telegram"></div>
            <h2 class="vert-margin30">Мы в Vk</h2>
            <div id="vk_groups"></div>
            <script type="text/javascript">
                VK.Widgets.Group("vk_groups", {mode: 0, width: "290", height: "290"}, 42392510);
            </script>

        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-sm-12">


            <h2>Найди попутчиков или попутную машину свою поездку!</h2>

            <p>
                Любите ли Вы природу так, как любим ее мы? Уверены, что да! Мы предлагаем реально действующую схему -
                ездим вместе и уменьшаем вредные выбросы в атмосферу. Только представьте - среднестатистическая
                легковушка выбрасывает за час в атмосферу столько углекислого газа, сколько способно надышать 100
                человек при сильной физической активности! Меньше машин на дороге - больше свежего воздуха. Поборемся за
                чистоту нашей планеты вместе!
            </p>
        </div>
    </div>

    <div class="row">

        <div class="col-md-4 col-sm-4">
            <h3>В некоторых городах слабо развит транспорт</h3>
            <p>Например, поезда ходят пару раз в неделю, а ехать в жарком и тесном автобусе очень некомфортно. С помощью
                нашего сервиса легко найти попутчика который едет на своем авто и поехать с ним</p>
        </div>
        <div class="col-md-4 col-sm-4">
            <h3>Водители ездят далеко в одиночку</h3>
            <p>Ехать одному несколько часов подряд скучно, даже с любимой музыкой. К тому же, удобнее было бы разделить
                расходы на горючее с пассажиром. Поиск попутчика в данном случае решает эту задачу.</p>
        </div>
        <div class="col-md-4 col-sm-4">
            <h3>Людям без машин приходится ездить поездами и автобусами</h3>
            <p>А в машине с кондиционером ехать комфортнее. Не все могут позволить себе автомобиль, но заплатить
                несколько сотен рублей за поездку могут многие.</p>
        </div>
    </div>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$title = 'Вход';

$this->title = Yii::$app->name . ' - ' . $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="site-login">
    <h1><?= Html::encode($title) ?></h1>

    <div class="row">
        <div class="col-md-6 col-sm-6">
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
            ]); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

                <?= Html::a('Регистрация', ['/site/register']); ?>
                |
                <?= Html::a('Забыли пароль?', ['/site/restore-password']); ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/partners.php
<?php

/* @var \yii\web\View $this */

$title = 'Наши партнеры';
$this->title = $title . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = $title;

?>

<h1><?= $this->title; ?></h1>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \app\models\RegistrationForm */

$title = 'Регистрация';

$this->title = Yii::$app->name . ' - ' . $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="site-register">
    <h1><?= Html::encode($title) ?></h1>

    <div class="row">
        <div class="col-md-6 col-sm-6">
            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
            ]); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <div class="form-group">
                <?= Html::submitButton('Зарегистрироваться', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>

            <?= Html::a('Войти', ['/site/login']); ?>
            |
            <?= Html::a('Забыли пароль?', ['/site/restore-password']); ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/restore-letter-sent.php
<?php

/* @var $this \yii\web\View */

?>

<div>
    <p>Новый пароль отправлен на e-mail</p>
</div>

views/site/restore-password.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\models\RestorePasswordForm */

$title = 'Восстановление пароля';

$this->title = Yii::$app->name . ' - ' . $title;
$this->params['breadcrumbs'][] = $title;
?>
<div class="restore-password">
    <h1><?= Html::encode($title) ?></h1>

    <div class="row">
        <div class="col-md-6 col-sm-6">
            <?php $form = ActiveForm::begin([
                'id' => 'restore-password-form',
            ]); ?>

            <?= $form->field($model, 'email')->textInput(['autofocus' => true]); ?>

            <div class="form-group">
                <?= Html::submitButton('Восстановить пароль', ['class' => 'btn btn-primary', 'name' => 'restore-password-button']); ?>
            </div>

            <?= Html::a('Регистрация', ['/site/register']); ?>
            |
            <?= Html::a('Вход', ['/site/login']); ?>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/rules.php
<?php

/* @var \yii\web\View $this */

$title = 'Правила сайта';
$this->title = $title . ' - ' . Yii::$app->name;

$this->params['breadcrumbs'][] = $title;

?>

<div class="site-rules">
    <h1>Правила пользования сервисом «Поехали вместе»</h1>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <h2>1. Общие положения</h2>
            <p>
                Водитель — водитель, берущий попутчиков, чтобы скрасить поездку или сократить расходы на поездку.
                <br />
                Пассажир – человек который ищет водителя для совершения поездки с ним по определенному маршруту
                <br /><br />
                1.1. Незнание или не прочтение Правил не освобождает от ответственности.
                <br />
                1.2. Если вы не нашли свое объявление, то оно могло быть удалено из-за нарушения. Не пытайтесь разместить новое, сначала разберитесь, что вы сделали не так.
                <br />
                1.3. Откровенно коммерческие предложения будут оставаться или удаляться по усмотрению Модератора.
            </p>

            <h2>2. Требования и ограничения.</h2>
            <p>
                2.1. Один Перевозчик — один аккаунт. Разные водители, разные транспортные средства — один аккаунт. Все объявления с других аккаунтов будут удаляться, зарегистрированные вновь блокироваться, основной подвергаться наказанию,
                Размещать «по просьбе» разрешено только Водителям и только с указанием ника основного Водителя.
                <br />
                2.2. Объявление должно содержать: <br />
                дату, направление, время выезда, тип транспорта, цену, количество пассажиров, контакты. Рекомендуется маршрут движения, место встречи с попутчиками и т.п.
                <br />
                2.3. Указывайте тип транспортного средства и марку и модель.
                <br />
                2.4. Указывайте количество посадочных мест. Если это пятиместный автомобиль, то обязательно указать, сколько будет попутчиков сзади.
            </p>

            <h2>3. Рекомендации.</h2>
            <p>
                3.1 с фото автомобиля объявление смотрится лучше. «Иномарка» — не марка. «Шевроле» — не марка. «Шевроле Лачетти» — марка.
                <br />
                3.2 указывайте по возможности маршруты движения (начальная, конечная и промежуточные точки), чтобы к общему удобству согласовать места встречи и места высадки;
                <br />
                3.3  внимательно читайте даты и направления.
                <br />
                3.4  оговаривайте условия заранее: когда платить, остановки, что можно, что нельзя делать в машине, будет ли довоз до подъезда и его условия и т.п.;
                <br />
                3.5 цены «стандарт», «автобусная», «договорная» не существует! Потрудитесь озвучивать;
                <br />
                3.6  представляйтесь при звонке. Нужно это не только по правилам хорошего тона, но и для последующей идентификации звонящего;
                <br />
                3.7 созванивайтесь для уточнения времени встречи и для подтверждения намерений за несколько часов, с тем, чтобы был всегда запасной вариант.
            </p>
        </div>
        <div class="col-md-4 col-sm-4">
        </div>
    </div>
</div>