controllers/AutoController.php
<?php

namespace app\controllers;


use app\models\Car;
use app\models\CarModel;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class AutoController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['create', 'update', 'delete'],
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                    'models' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index', [

        ]);
    }

    /**
     * @return string
     */
    public function actionCreate()
    {
        $model = new Car();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('/profile/view');
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionUpdate($id)
    {
        $model = $this->findUserModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect('/profile/view');
        }

        return $this->render('form', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @param $id
     * @return \yii\web\Response
     * @throws NotFoundHttpException
     */
    public function actionDelete($id)
    {
        $model = $this->findUserModel($id);
        $model->status = Car::STATUS_DELETED;
        $model->save();

        return $this->redirect('/profile/view');
    }

    public function actionModels()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $id = Yii::$app->request->post('id');
        if (!$id) {
            return [];
        }

        return CarModel::find()->select(['id', 'name'])->where(['mark_id' => $id])->orderBy(['name' => SORT_ASC])->asArray()->all();
    }

    /**
     * @param $id
     * @return Car
     * @throws NotFoundHttpException
     */
    protected function findModel($id)
    {
        $model = Car::find()->with(['user'])->where(['id' => $id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }

    /**
     * @param $id
     * @return Car
     * @throws NotFoundHttpException
     */
    protected function findUserModel($id)
    {
        $model = Car::find()->where(['id' => $id, 'user_id' => Yii::$app->user->id, 'status' => Car::STATUS_ACTIVE])->one();

        if ($model === null) {
            throw new NotFoundHttpException();
        }

        return $model;
    }
}

views/auto/form.php
<?php

use app\models\Car;
use app\models\CarMark;
use app\models\CarModel;
use yii\widgets\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model Car */

$this->title = $model->isNewRecord ? 'Добавление автомобиля' : 'Редактирование автомобиля';

$this->params['breadcrumbs'][] = [
    'label' => 'Автомобили',
    'url' => ['/auto/index'],
];

$this->params['breadcrumbs'][] = [
    'label' => $model->getTitle(),
    'url' => ['/auto/view', 'id' => $model->id],
];

$this->params['breadcrumbs'][] = 'Редактирование';


?>

<div class="auto-form">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <h1><?= Html::encode($this->title); ?></h1>
        </div>

        <?php $form = ActiveForm::begin([]); ?>

        <div class="col-md-6 col-sm-6">
            <?= $form->field($model, 'mark_id')->dropDownList(CarMark::getDropdownList(), [
                'class' => 'form-control select2',
                'id' => 'car-mark',
                'prompt' => '- Выбрать -',
            ]); ?>
        </div>
        <div class="col-md-6 col-sm-6">
            <?= $form->field($model, 'model_id')->dropDownList(CarModel::getDropdownList($model->mark_id), [
                'id' => 'car-model',
                'prompt' => '- Выбрать -',
            ]); ?>
        </div>

        <div class="col-md-6 col-sm-6">
            <?= $form->field($model, 'year')->dropDownList(Car::getYears(), [
                'class' => 'form-control select2',
                'prompt' => '- Выбрать -',
            ]); ?>
        </div>
        <div class="col-md-6 col-sm-6">
            <?= $form->field($model, 'capacity')->textInput(); ?>
        </div>
        <div class="col-md-12 col-sm-12">
            <?= $form->field($model, 'description')->textarea(); ?>
        </div>

        <div class="col-md-12 col-sm-12">
            <div class="form-group">
                <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/auto/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Авто наших водителей';

?>

<div class="auto-index">
    <h1><?= $this->title; ?></h1>
</div>

views/auto/view.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model \app\models\Car */

$this->title = 'Автомобиль ' . $model->getTitle();

$this->params['breadcrumbs'][] = [
    'label' => 'Автомобили',
    'url' => ['/auto/index'],
];

$this->params['breadcrumbs'][] = $this->title;

$town = $model->user->town;
?>

<div class="auto-view">
    <div class="row">
        <div class="col-md-12 col-sm-12">
        <h1><?= Html::encode($this->title); ?></h1>
        </div>
        <div class="col-md-6 cols-sm-6">

            <h2>Владелец</h2>
            <?= Html::a(
                Html::img('/img/thumbs/user.jpg', [
                    'class' => 'avatar',
                    'alt' => Html::encode($model->user ? $model->user->name : 'unknown'),
                ]), ['/profile/view', 'id' => $model->user->id]
            ); ?>
            <?= Html::a(Html::encode($model->user->name), ['/profile/view', 'id' => $model->user->id]); ?>
            <?php if ($town) { ?>
                <?= Html::a(Html::encode($town->name), $town->getUrl()); ?>
            <?php } ?>

            <h2>Описание машины</h2>
            <?= 'Год выпуска: ' . $model->year . '<br/>'; ?>
            <?php if ($model->description) { ?>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?= $model->description; ?>
                    </div>
                </div>
            <?php } ?>
        </div>
        <div class="col-md-6 cols-sm-6">
            <h2>Фотографии машины</h2>
        </div>
    </div>
</div>