models/Trip.php
<?php

namespace app\models;


/**
 * This is the model class for table "trip".
 *
 * @property int $id
 * @property int $type 1-ищу водителя, 2-ищу пассажира
 * @property int $user_id
 * @property string $trip_time
 * @property string $town_from
 * @property string $town_to
 * @property int $from_id
 * @property int $to_id
 * @property string $from_place
 * @property string $to_place
 * @property int $driver_id
 * @property int $passengers
 * @property string $description
 * @property int $price
 * @property int $periodic
 * @property int $car_id
 * @property int $views
 * @property int $status 0-неактивная, 10-активная, 20-законченная, -10-удалена
 * @property string $created_at
 *
 * @property GeoTown $from
 * @property GeoTown $to
 * @property Car $car
 * @property User $user
 */
class Trip extends \yii\db\ActiveRecord
{
    public const TYPE_FIND_DRIVER = 1;
    public const TYPE_FIND_PASSENGERS = 2;

    public const STATUS_INACTIVE = 0;
    public const STATUS_ACTIVE = 10;
    public const STATUS_FINISHED = 20;
    public const STATUC_DELETED = -10;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'trip';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['type', 'user_id', 'trip_time', 'from_id', 'to_id'], 'required'],
            [['type'], 'in', 'range' => array_keys(static::getTypeList())],
            [['user_id', 'from_id', 'to_id', 'driver_id', 'price', 'car_id'], 'integer'],
            [['passengers'], 'integer', 'min' => 1],
            [['trip_time'], 'safe'],
            [['description'], 'string'],
            [['town_from', 'town_to', 'from_place', 'to_place'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'user_id' => 'User ID',
            'trip_time' => 'Trip Time',
            'town_from' => 'Town From',
            'town_to' => 'Town To',
            'from_id' => 'From ID',
            'to_id' => 'To ID',
            'from_place' => 'From Place',
            'to_place' => 'To Place',
            'driver_id' => 'Driver ID',
            'passengers' => 'Passengers',
            'description' => 'Description',
            'price' => 'Price',
            'periodic' => 'Periodic',
            'car_id' => 'Car ID',
            'views' => 'Views',
            'status' => 'Status',
            'created_at' => 'Created At',
        ];
    }

    /**
     * @return array
     */
    public static function getTypeList()
    {
        return [
            static::TYPE_FIND_DRIVER => 'Ищу водителя',
            static::TYPE_FIND_PASSENGERS => 'Ищу пассажиров',
        ];
    }

    /**
     * @return array
     */
    public static function getStatusList()
    {
        return [
            static::STATUS_INACTIVE => 'Неактивная',
            static::STATUS_ACTIVE => 'Активная',
            static::STATUS_FINISHED => 'Завершенная',
            static::STATUC_DELETED => 'Удаленная',
        ];
    }

    /**
     * @param $id
     * @return Trip|null
     */
    public static function findById($id)
    {
        return static::find()
            ->where(['id' => $id])
            ->andWhere(['in', 'status', [static::STATUS_ACTIVE, static::STATUS_FINISHED]])
            ->one();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFrom()
    {
        return $this->hasOne(GeoTown::class, ['id' => 'from_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTo()
    {
        return $this->hasOne(GeoTown::class, ['id' => 'to_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCar()
    {
        return $this->hasOne(Car::class, ['id' => 'car_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\services\UserService;
use app\models\ContactForm;
use app\models\GeoTown;
use app\models\LoginForm;
use app\models\RegistrationForm;
use app\models\RestorePasswordForm;
use app\models\SearchForm;
use app\models\User;
use Yii;
use yii\base\Exception;
use yii\captcha\CaptchaAction;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\ErrorAction;
use yii\web\Response;

/**
 * Class SiteController
 * @package app\controllers
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                    'town' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
            'captcha' => [
                'class' => CaptchaAction::class,
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchForm = new SearchForm();

        return $this->render('index', [
            'searchForm' => $searchForm,
        ]);
    }

    /**
     * @return array
     */
    public function actionTown()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        return GeoTown::findByTerm(Yii::$app->request->post('query'));
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRestorePassword()
    {
        $model = new RestorePasswordForm();

        if ($model->load(Yii::$app->request->post()) && $model->resetPassword() && $model->sendLetter()) {
            return $this->render('restore-letter-sent');
        }

        return $this->render('restore-password', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionRegister()
    {
        $model = new RegistrationForm();

        if ($model->load(Yii::$app->request->post()) && $model->process()) {
            $user = $model->getUser();
            Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения регистрации');
            return $this->redirect(['/site/index']);
        }

        return $this->render('register', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $email
     * @param string $code
     * @return Response
     */
    public function actionConfirm($email, $code)
    {
        $user = User::findOne([
            'email' => $email,
            'confirm_code' => $code,
            'status' => User::STATUS_INACTIVE
        ]);

        if ($user === null) {
            Yii::$app->session->setFlash('error', 'Пользователь с такими данными не найден, либо не требует активации');
            return $this->redirect(['index']);
        }

        if (UserService::confirm($user)) {
            Yii::$app->session->setFlash('success', 'Ваш аккаунт активирован');
            Yii::$app->user->login($user);
            return $this->redirect(['/profile/view']);
        }

        Yii::$app->session->setFlash('error', 'Возникла непредвиденная ошибка. Обратитесь в службу поддержки');
        return $this->redirect(['index']);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string
     */
    public function actionCalculator()
    {
        return $this->render('calculator');
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionFeedback()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('feedback', [
            'model' => $model,
        ]);
    }

    /**
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * @return string
     */
    public function actionSafety()
    {
        return $this->render('safety');
    }

    /**
     * @return string
     */
    public function actionRules()
    {
        return $this->render('rules');
    }

    /**
     * @return string
     */
    public function actionPartners()
    {
        return $this->render('partners');
    }
}

controllers/TripsController.php
<?php

namespace app\controllers;


use app\components\services\TripService;
use app\models\Step2Form;
use app\models\Step3Form;
use Yii;
use app\components\Dumper;
use app\models\GeoCountry;
use app\models\GeoRegion;
use app\models\GeoTown;
use app\models\Step1Form;
use app\models\Trip;
use yii\base\Exception;
use yii\db\ActiveRecord;
use yii\helpers\VarDumper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class TripsController
 * @package app\controllers
 */
class TripsController extends Controller
{
    public function actionSearch()
    {

    }

    public function actionIndex()
    {
        return $this->render('index', [

        ]);
    }

    /**
     * @return string
     * @throws Exception
     */
    public function actionCreate()
    {
        $step = Yii::$app->session->get('step', 1);

        // сверяем шаг в сессии и в ссылке
        $get = Yii::$app->request->get();
        for ($i = 1; $i <= 3; $i++) {
            if ($step == $i && !array_key_exists("step$i/", $get)) {
                // если не совпадает, редиректим на нужный
                return $this->redirect(["/trips/create/?step$step/"]);
            }
        }

        switch ($step) {
            case 2:
                $model = new Step2Form();
                break;
            case 3:
                $model = new Step3Form();
                break;
            default:
                $model = new Step1Form();
        }

        if (Yii::$app->request->isGet && $step !== 1) {
            $model->attributes = Yii::$app->session->get('stepForm');
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($step === 3 && $model->process()) {
                $user = $model->getUser();
                Yii::$app->session->remove('step');
                Yii::$app->session->remove('stepForm');
                if ($user) {
                    Yii::$app->session->setFlash('success', 'На адрес ' . $user->email . ' отправлено письмо с инструкцией для подтверждения поездки');
                } else {
                    Yii::$app->session->setFlash('error', $model->getError());
                }
                return $this->redirect('/');
            }
            $step++;
            // пишем шаг в сессию
            Yii::$app->session->set('step', $step);
            // пишем в сессию данные модели
            Yii::$app->session->set('stepForm', $model->attributes);
            return $this->redirect(["/trips/create/?step$step/"]);
        }

        return $this->render('step' . $step, [
            'model' => $model,
        ]);
    }

    /**
     * @param $country
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionCountry($country)
    {
        $countryModel = $this->getCountryByAlias($country);

        return $this->render('country', [
            'country' => $countryModel,
            'region'  => null,
            'town'    => null,
        ]);
    }

    /**
     * @param $country
     * @param $region
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionRegion($country, $region)
    {
        $countryModel = $this->getCountryByAlias($country);
        $regionModel = $this->getRegionByAlias($region);

        return $this->render('region', [
            'country' => $countryModel,
            'region'  => $regionModel,
            'town'    => null,
        ]);
    }

    /**
     * @param $country
     * @param $region
     * @param $town
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionTown($country, $region, $town)
    {
        $countryModel = $this->getCountryByAlias($country);
        $regionModel = $this->getRegionByAlias($region);
        $townModel = $this->getTownByAlias($town);

        return $this->render('town', [
            'country' => $countryModel,
            'region'  => $regionModel,
            'town'    => $townModel,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id)
    {
        $model = Trip::findById($id);

        $this->checkNull($model);

        TripService::incrementViews($model);

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @param string $alias
     * @return GeoCountry
     * @throws NotFoundHttpException
     */
    protected function getCountryByAlias($alias)
    {
        $model = GeoCountry::getByAlias($alias);

        $this->checkNull($model);

        return $model;
    }

    /**
     * @param $alias
     * @return GeoRegion
     * @throws NotFoundHttpException
     */
    protected function getRegionByAlias($alias)
    {
        $model = GeoRegion::getByAlias($alias);

        $this->checkNull($model);

        return $model;
    }

    /**
     * @param $alias
     * @return GeoTown
     * @throws NotFoundHttpException
     */
    protected function getTownByAlias($alias)
    {
        $model = GeoTown::getByAlias($alias);

        $this->checkNull($model);

        return $model;
    }

    /**
     * @param ActiveRecord $model
     * @throws NotFoundHttpException
     */
    protected function checkNull($model)
    {
        if ($model === null) {
            throw new NotFoundHttpException();
        }
    }

}

views/trips/_trips.php
<?php

/* @var \yii\web\View $this */

?>

<div class="col-md-7 col-sm-7">
trips...
</div>

views/trips/country.php
<?php

use app\widgets\GeoWidget;
use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \app\models\GeoCountry|null $country */

$title = Html::encode($country->name);
$this->title = 'Попутчики ' . $title . ' в совместные поездки на автомобиле';

$this->params['breadcrumbs'][] = $title;

?>

<div class="trips-country">
    <div class="col-md-2 col-sm-2">
        <?= GeoWidget::widget(['model' => $country]); ?>
    </div>
    <div class="col-md-7 col-sm-7">
        <h1><?= $title; ?></h1>
        <?= $this->render('_trips'); ?>
    </div>
</div>

views/trips/index.php
<?php

/* @var $this yii\web\View */


?>

<div class="trips-index">

</div>

views/trips/region.php
<?php

use app\widgets\GeoWidget;
use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \app\models\GeoCountry|null $country */
/* @var \app\models\GeoRegion|null $region */

$title = Html::encode($region->name);
$this->title = 'Попутчики на машине ' . $title;

$this->params['breadcrumbs'][] = [
    'label' => Html::encode($country->name),
    'url'   => $country->getUrl(),
];

$this->params['breadcrumbs'][] = $title;

?>

<div class="trips-region">
    <div class="col-md-2 col-sm-2">
        <?= GeoWidget::widget(['model' => $region]); ?>
    </div>
    <div class="col-md-7 col-sm-7">
        <h1><?= $title; ?></h1>
        <?= $this->render('_trips'); ?>
    </div>
</div>

views/trips/step1.php
<?php

use app\models\Trip;
use yii\helpers\Html;

/* @var $this View */
/* @var $model \app\models\Step1Form */

$this->title = 'Новая поездка';

use yii\web\View;
use yii\widgets\ActiveForm; ?>

<div class="row">
    <div class="col-md-8 col-sm-8 vert-margin40">
        <h1><?= $this->title; ?></h1>
        <?php $form = ActiveForm::begin(); ?>

        <div class="form-group">
            <?= Html::submitButton('Я пассажир', [
                'class' => 'btn btn-success select-role-btn',
                'name' => 'Step1Form[type]',
                'value' => Trip::TYPE_FIND_DRIVER,
            ]); ?>
            <?= Html::submitButton('Я водитель', [
                'class' => 'btn btn-success select-role-btn',
                'name' => 'Step1Form[type]',
                'value' => Trip::TYPE_FIND_PASSENGERS
            ]); ?>
        </div>
        <?php ActiveForm::end(); ?>
    </div>
</div>

views/trips/step2.php
<?php

use app\models\Car;
use app\models\CarMark;
use app\models\CarModel;
use app\models\Step2Form;
use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model Step2Form */

$this->title = 'Новая поездка';

?>

<div class="row">
    <div class="col-md-8 col-sm-8 vert-margin40">
        <h1><?= $this->title; ?></h1>

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->errorSummary($model) ?>

        <div class="row">
            <div class="col-lg-4">
                <?= $form->field($model, 'fromId')->dropDownList([], [
                    'prompt' => 'Откуда едем',
                    'class' => 'form-control select-town',
                    'data' => [
                        'ajax--url' => Url::to(['/site/town'], true),
                    ],
                ])->label(false) ?>
            </div>
            <div class="col-lg-4">
                <?= $form->field($model, 'toId')->dropDownList([], [
                    'prompt' => 'Куда едем',
                    'class' => 'form-control select-town',
                    'data' => [
                        'ajax--url' => Url::to(['/site/town'], true),
                    ],
                ])->label(false) ?>
            </div>

            <div class="col-lg-4">
                <div class="form-group">
                    <?= $form->field($model, 'date')->widget(DateTimePicker::class, [
                        'type' => DateTimePicker::TYPE_INPUT,
                        'options' => [
                            'placeholder' => 'Когда',
                        ],
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd.mm.yyyy hh:ii',
                            'language' => 'ru',
                        ]
                    ])->label(false); ?>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4">
                <?= $form->field($model, 'wayBack')->checkbox(); ?>
            </div>
            <div class="col-lg-4 date-back" style="display:none;">
                <div class="form-group">
                    <?= $form->field($model, 'dateBack')->widget(DateTimePicker::class, [
                        'type' => DateTimePicker::TYPE_INPUT,
                        'options' => [
                            'placeholder' => 'Когда',
                        ],
                        'pluginOptions' => [
                            'autoclose'=>true,
                            'format' => 'dd.mm.yyyy hh:ii',
                            'language' => 'ru',
                        ]
                    ])->label(false); ?>
                </div>
            </div>
        </div>

        <?php if ($model->type == \app\models\Trip::TYPE_FIND_PASSENGERS) { ?>
            <div class="row">
                <div class="col-md-4 col-sm-4">
                    <?= $form->field($model, 'carMarkId')->dropDownList(CarMark::getDropdownList(), [
                        'class' => 'form-control select2',
                        'id' => 'car-mark',
                        'prompt' => '- Выбрать -',
                    ]); ?>
                </div>
                <div class="col-md-4 col-sm-4">
                    <?= $form->field($model, 'carModelId')->dropDownList(CarModel::getDropdownList($model->carMarkId), [
                        'class' => 'form-control select2',
                        'id' => 'car-model',
                        'prompt' => '- Выбрать -',
                    ]); ?>
                </div>

                <div class="col-md-4 col-sm-4">
                    <?= $form->field($model, 'carYear')->dropDownList(Car::getYears(), [
                        'class' => 'form-control select2',
                        'prompt' => '- Выбрать -',
                    ]); ?>
                </div>
            </div>
        <?php } ?>

        <div class="form-group">
            <?= Html::submitButton('Далее', [
                'class' => 'btn btn-primary',
            ]) ?>
        </div>

        <?= $form->field($model, 'type')->hiddenInput()->label(false); ?>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/trips/step3.php
<?php

use app\models\Step3Form;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model Step3Form */

$this->title = 'Новая поездка';
?>

<div class="row">
    <div class="col-md-8 col-sm-8 vert-margin40">
        <h1><?= $this->title; ?></h1>

        <?php $form = ActiveForm::begin(); ?>

        <?= $form->errorSummary($model) ?>

        <?= $form->field($model, 'name') ?>
        <?= $form->field($model, 'email') ?>
        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::submitButton('Сохранить', [
                'class' => 'btn btn-primary',
            ]) ?>
        </div>

        <?= $form->field($model, 'type')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'fromId')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'toId')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'date')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'carMarkId')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'carModelId')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'carYear')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'wayBack')->hiddenInput()->label(false) ?>
        <?= $form->field($model, 'dateBack')->hiddenInput()->label(false) ?>

        <?php ActiveForm::end(); ?>
    </div>
</div>

views/trips/success.php
<?php

use yii\web\View;

/* @var $this View */

$this->title = 'Подтверждение';

?>

<div class="trips-success">
    На ваш адрес отправлено письмо с инструкциями для подтверждения поездки
</div>

views/trips/town.php
<?php

use yii\helpers\Html;

/* @var \yii\web\View $this */
/* @var \app\models\GeoCountry|null $country */
/* @var \app\models\GeoRegion|null $region */
/* @var \app\models\GeoTown|null $town */

$title = Html::encode($town->name);
$this->title = 'Попутчики из/в ' . $title . ' на машине';

$this->params['breadcrumbs'][] = [
    'label' => Html::encode($country->name),
    'url'   => $country->getUrl(),
];

$this->params['breadcrumbs'][] = [
    'label' => Html::encode($region->name),
    'url'   => $region->getUrl(),
];

$this->params['breadcrumbs'][] = $this->title;

?>

<div class="trips-town">
    <div class="town-photo">
        photo
    </div>
    <div class="row">
        <div class="col-md-8 col-sm-8">
            <h1>Объявления о поиске попутчиков из/в <?= $title; ?></h1>
            <?= $this->render('_trips'); ?>
        </div>
        <div class="col-md-4 col-sm-4">
            Попутчики из этого города
        </div>
    </div>
</div>

views/trips/view.php
<?php

use yii\helpers\Html;
use app\components\StringHelper;
use app\models\Trip;

/* @var $this yii\web\View */
/* @var $model \app\models\Trip */

$passengerIcon = '<div class="trip-icon" title="Кол-во пассажиров"><i class="fas fa-user"></i></div>';
$carIcon = '<div  class="trip-icon" title="Автомобиль"><i class="fas fa-car"></i></div>';
$clockIcon = '<div class="trip-icon" title="Время выезда"><i class="fas fa-clock"></i></div>';
$rubIcon = '<div class="trip-icon" title="Стоимость поездки"><i class="fas fa-ruble-sign "></i></div>';
$viewsIcon = '<div class="trip-icon" title="Просмотров"><i class="fas fa-eye "></i></div>';

$townFrom = Html::encode($model->town_from);
$townTo = Html::encode($model->town_to);

$this->title = 'Попутчики ' . $townFrom . ' - ' . $townTo . '. На машине ' .
    StringHelper::mb_ucfirst(Yii::$app->formatter->asDate($model->trip_time, 'php:D d M Y H:i')) . '. ' .
    Yii::$app->name;

$this->params['breadcrumbs'][] = [
    'label' => 'Объявления',
    'url' => ['/trips/index']
];
$this->params['breadcrumbs'][] = $townFrom . ' - ' . $townTo;

$car = $model->car ? Html::encode($model->car->manufacturer) . '&nbsp;' . Html::encode($model->car->model) : '';
$userName = Html::encode($model->user->name);

\app\assets\YMapsAsset::register($this);

?>

    <div class="row">
        <div class="col-md-8 col-sm-8 vert-margin40">
            <h1><?= 'Попутчики' . ' ' . $townFrom . '&nbsp;&rarr;&nbsp;' . $townTo; ?></h1>
            <div class="row vert-margin40">
                <div class="col-md-4 col-sm-1 center-align">
                    <?= Html::a(
                        Html::img('/img/thumbs/user150.jpg', [
                            'alt' => Html::encode($model->user->name),
                        ]), ['/profile/view', 'id' => $model->user->id]
                    ); ?>
                </div>
                <div class="col-md-8 col-sm-11">
                    <h2>Информация о поездке:</h2>

                    <div class="lead">
                        <?= Html::a($userName, ['/profile/view', 'id' => $model->user->id]); ?> ищет
                        <?= $model->type === Trip::TYPE_FIND_PASSENGERS ? 'пассажиров' : 'водителя'; ?> на
                        <u><?= StringHelper::mb_ucfirst(Yii::$app->formatter->asDate($model->trip_time, 'php:D d M Y')); ?></u>
                    </div>
                    <?= \app\widgets\TripIconsWidget::widget([
                        'model' => $model,
                    ]); ?>
                </div>
            </div>

            <?php if (!empty($model->description)) { ?>
                <div class="row">
                    <div class="col-md-12 col-sm-12">
                        <h2>Комментарий автора к поездке
                        </h2>
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <?= $model->description; ?>
                            </div>
                        </div>
                    </div>
                </div>
            <?php } ?>

            <div class="row">
                <div class="col-md-12 col-sm-12">
                    <h2>Маршрут на карте (ориентировочный)</h2>
                    <p><strong>*Маршрут строится автоматически и может отличаться от реального!</strong></p>
                    <div id="ymap" style="width:100%;height:400px;">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-sm-4 hidden-xs">
            <button type="button" class="btn btn-lg btn-block btn-default">Откликнуться</button>
            <button type="button" class="btn btn-lg btn-block btn-default">Создать свою поездку</button>
        </div>
    </div>


<?php
$townFrom = $model->town_from;
$townTo = $model->town_to;
$this->registerJs(
    <<<JS

var map;
var townFrom = "$townFrom";
var townTo = "$townTo";

ymaps.ready(initMap);

function initMap()
{
    map = new ymaps.Map('ymap', {
        center: [55.76, 37.64],
        zoom: 10
    }, {
        searchControlProvider: 'yandex#search'
    });
    
    var route = new ymaps.multiRouter.MultiRoute({   
        referencePoints: [
            townFrom,
            townTo
        ]
    }, {
        boundsAutoApply: true
    });
    
    map.geoObjects.add(route);
    
    route.events.once('update', function() {
        route.getActiveRoute().balloon.open();
    });
    
}

JS
);